#!/bin/sh

: "${OCIS_DOMAIN:='localhost:9200'}"

sed -e "s|ocis.example.org|${OCIS_DOMAIN}|g" /config/identifier-registration.yaml.tmpl > /config/identifier-registration.yaml
ls /usr/bin
sleep 999999999
#exec /usr/bin/ocis server
